<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PermissionController extends AbstractBaseController
{
    public $_autorender = false;
    // $role->syncPermissions($permissions);
    // $permission->syncRoles($roles);


    public function index()
    {
        parent::index(); // TODO: Change the autogenerated stub

        return $this->ResolveViewPath();
    }
}
